NetrunnerDB/netrunner-cards-json

set/dt.json
set/fc.json
set/hap.json
set/hs.json
set/si.json
set/st.json
set/uao.json
set/wla.json

Doing this via the web so I haven't squashed everything into 1 commit (only just learned how to do that last week, haha).

another set of typo corrections

---

pack/tlm.json

Corrected Advancement / Point values on Dedicated Neural Net (The Liberated Mind #88)

Dedicated Neural Net correction

---

pack/23s.json

taken from https://www.fantasyflightgames.com/en/news/2016/5/31/android-archived-memories-6-2016/

add "Stock Buy-Back"

---

pack/bm.json

Temüjin Contract is the 26th card.

fix position for temüjin contract

---

pack/cac.json
pack/core.json
pack/fc.json
pack/kg.json

According to today's release, this becomes effective on 18 July.

Card errata in FAQ 3.1

---

pack/tc.json

this is from pg 11 of the FAQ, no idea why it's not in the errata list

Add errata for Punitive Counterstrike

---

pack/ml.json

Mistakenly left IP Block on Weyland 😅 . This fixes it!

Fix faction for IP Block

---

pack/bm.json
pack/ml.json

Minor tweaks to IP Block, Aiki, and C.I. Fund.

Blood Money and Martial Law fixes

---

packs.json

https://www.fantasyflightgames.com/en/news/2016/10/6/available-this-week-10/

Added Escalation release date

---

pack/es.json

Adam flavor and rest card pics

---

packs.json

Intervention street date was yesterday.

add Intervention release date

---

pack/ml.json

Scoops image [here](http://imgur.com/a/x1S3p).

Add new Martial Law card data from FFG Worlds scoops

---

pack/ml.json

The card image shows "suffers" instead of "takes"...

change text of last Fairchild subroutine

---

pack/eas.json

from https://images-cdn.fantasyflightgames.com/filer_public/ae/25/ae250e29-27e3-4f39-a076-df78cfaad417/adn45-adjusted-matrix.png

fix Adjusted Matrix text

---

pack/so.json

remove influence from Self-Adapting Code Wall

---

pack/qu.json

Advancement target for the HB agenda and influence of 0 for the two pieces of neutral ICE have been confirmed on reddit.

add remaining Quorum Corp cards

---

pack/in.json

unified spelling of “G-Mod”

---

pack/ml.json

Changed Thoth uniqueness to 'true'.

Thoth uniqueness set to 'true'

---

pack/td.json

from https://www.reddit.com/r/Netrunner/comments/5rmtke/gtm_spoils_terminal_directive_criminal_identity/

add Steve Cambridge

---

pack/es.json
translations/kr/cycles.kr.json

Reverts zaroth/netrunner-cards-json#168
You edited es.json instead of es.kr.json

Revert "Update cycles.kr.json"

---

pack/td.json

Announcement [here](https://www.fantasyflightgames.com/en/news/2017/3/1/a-new-directive/)
Images:
- [Officer Frank](https://images-cdn.fantasyflightgames.com/filer_public/74/37/743790db-9b07-4ab0-8f3e-222e2daff71d/adn42-officer-frank.png)
- [Eli 2.0](https://images-cdn.fantasyflightgames.com/filer_public/75/79/75795c08-e388-4d77-b48c-bc42e89e03c8/adn42-eli-2-0.png)

Add 2 new cards spoiled in the latest announcement for Terminal Directive

---

pack/td.json

Spoilers links:
- [Ubax](https://twitter.com/FFGames/status/841736520960741376)
- [Laguna Velasco District](https://twitter.com/FFGames/status/841736938184970240)
Images:
- [Ubax](https://pbs.twimg.com/media/C65ypDVXEAAzdCw.png) 
- [Laguna Velasco District](https://pbs.twimg.com/media/C65zRXIWgAMGdoa.png)

Add new twitter spoilers for Terminal Directive

---

translations/it/pack/bf.it.json
translations/it/pack/ce.it.json

Added the italian translations for Cyber Exodus and Business First.

Added italian translations for ce and bf

---

pack/td.json

Link here: https://www.instagram.com/p/BR4pbz1DN8r/

Add spoiled Terminal Directive cards in Theology games instagram

---

pack/td.json

- [Extra cards spoiled](https://www.instagram.com/p/BR9n_ftD4vy/) by Theology Games
- [Card spoiled](https://i.imgur.com/CuqOxc3.png) during Damon and Team Covenant's [preview of Terminal Directive](https://www.youtube.com/watch?v=8heuAYo3iaM)

More TD spoiled cards

---

pack/td.json

Link here: https://twitter.com/FFGames/status/844967734706343938
Also, fixed the memory code used in Polyhistor.

New TD spoiled card on FFG twitter feed.

---

pack/cac.json
pack/dc.json
pack/hap.json
pack/mt.json
pack/oac.json
pack/so.json
pack/td.json

Link to FAQ file:
https://images-cdn.fantasyflightgames.com/filer_public/01/f0/01f0cd58-eed3-4f6d-a43d-738ccb2156b6/adn_faq_40.pdf
These changes are in effect from the **2th June 2017**.

Update cards wording with new errata from FAQ 4.0

---

pack/eas.json

Earth's Scion fixes

---

translations/jp/cycles.jp.json
translations/jp/factions.jp.json
translations/jp/pack/cac.jp.json
translations/jp/pack/oac.jp.json
translations/jp/packs.jp.json

I translated the "Creation and Control" card texts into Japanese.

Translated the "Creation and Control" into Japanese

---

translations/de/pack/baw.de.json
translations/de/pack/eas.de.json
translations/de/pack/qu.de.json
translations/de/pack/td.de.json
translations/de/packs.de.json

Translations added for:
* Quorum
* Terminal Directive
* Blood and Water
* Earth's Scion
Also added some missing pack title translations.

Add german translations

---

packs.json

Press release: https://www.fantasyflightgames.com/en/news/2017/8/17/all-sectors-on-alert

Add Crimson Dust release date

---

translations/de/pack/dag.de.json
translations/de/pack/in.de.json
translations/de/pack/kg.de.json
translations/de/pack/ml.de.json
translations/de/pack/tlm.de.json

Added a few more translations.
This closes #236, closes #239, closes #235 and closes #233.

Add german translations of a few data packs

---

translations/de/pack/core2.de.json

Closes #252.
Just copy/pasted, I did not check for any errors.

Add german translation for Core 2.0

---

translations/de/pack/dc.de.json
translations/de/pack/si.de.json

Add german translation for Daedalus Complex and Salsette Island

---

pack/ss.json

Fix typos in Zamba's flavor text

---

pack/ts.json

fix a typo in Au Revoir flavor text

---

pack/ss.json

Illustrator name for Mganga corrected (incorrect name appears in the illustrator drop down on Card Search)

 Minor typo for Mganga

---

pack/tdatd.json

Looks like it's only 1 influence https://i.imgur.com/etnGWcJ.jpg

Update Malia influence cost

---

factions.json
schema/faction_schema.json

Translated by
[https://gist.github.com/MicahElliott/719710#file-colortrans-py](https://gist.github.com/MicahElliott/719710#file-colortrans-py). Some of these look a little off to me, but they're at least a good start.  (I've made a command-line-based deckbuilder, so this does have a practical, if very niche, application.)

Add xterm colours

---

pack/rar.json

Change "trashed" to "uninstalled" and add "Limit 1 per deck."

Match card text for DJ Fenris

---

rotations.json

Other deluxe cycles are also declared via cycle code here.

Use code of cycle instead of pack for RaR

---

translations/de/cycles.de.json
translations/de/pack/rar.de.json
translations/de/packs.de.json

This is then my last PR for this repo.
Thank you @gereons for all your reviews!
You most likely will find some typos in this one. :wink:

Add german translation of Reign and Reverie

---

pack/rar.json

Game Changer should have a trash cost of 2
https://netrunnerdb.com/find/?q=Game+Changer

Added trash cost to Game Changer

---

pack/sc19.json

Validation didn't catch this as `cost` isn't a required field.

Adds Cost to cards where missing

---

schema/card_schema.json
validate.py

Also cleans up whitespace in `validate.py`

Add cost checking to card schema

---

mwl.json

Set effective date as 21st December as per NISEI comms, although many people are adopting SC19 and this MWL already.

Added Standard MWL 3.0

---

schema/card_schema.json
schema/cycle_schema.json
schema/faction_schema.json
schema/pack_schema.json
schema/side_schema.json
schema/type_schema.json

After #372, I realized that more could be done to strengthen the card validation schema. So after reading the json-schema documentation, I've gotten this far.

Additional Card Validation

---

cycles.json
pack/ad.json
packs.json

~Still need the cycle.json and pack.json files, but this is a good start.~ Done!

Ashes: Cycle and Packs, with The Nihilist, The Class Act, The Artist

---

pack/df.json

Fix incorrect text

---

pack/df.json

Remove Bioriod Subtype

---

pack/df.json

Update Rezeki's position

---

pack/df.json

As per http://nisei.net/article/2019AScoop7.
Please find my mistakes! 😛

Added Letheia Nisei

---

pack/df.json

Once per run instead of once per turn.

Fixed typo on Utae

---

pack/core.json

Capitalize "his" in second sentence

Correct Hadrian's Wall flavor text

---

pack/df.json

Added period to Hyoubu flavor text and fixed subroutine spacing/capitalization on Trebuchet trace sub

More copy-editing

---

pack/td.json

Fixed capitalized "Trace" on Paper Trail and missing period on IPO

Copy-editing

---

pack/rar.json

* Place all of Mache's cost within `<strong>` tags
* Correct missing word in Too Big to Fail's flavor text
* Add missing period to end of Otoroshi's flavor text

Fix small typos in RAR

---

pack/dad.json
pack/mo.json
pack/om.json

Typos spotted by Jamie and MrBuggles in NISEI.

Fixed typos in card text

---

pack/ss.json
pack/td.json

Shout-outs to Jamie for catching these.

Fix Gene Splicer, add errata to Charlatan

---

pack/sc19.json

My bad, only updated the original card from First Contact when I submitted #455. 🤦‍♂

Remebered to add this errata for the SC19 card as well

---

pack/ur.json
packs.json

I've already uploaded the spoiled full bleed card image to production, so it's ready to go...
I put a placeholder release date for Uprising of end of the year, although we expect it to be before NYE itself!

Added Swift (newly spoiled Crim Console) and Uprising pack

---

pack/ur.json

`<em>` within FT will un-italicize. Replacing a `<strong>` tag with `<em>` to better reflect card.

Replace <strong> in Simulchip FT

---

pack/ur.json

Followed the standard set by Red Level Clearance.

Properly format list in Wall to Wall's text

---

pack/ur.json

Corrected influence cost on Gachapon

---

pack/mt.json

As requested by NISEI Rules Team.

Removed mention of FAQ 4.0 errata

---

pack/mo.json
pack/mor.json

Name update for Jess Horig on Slot Machine.

Slot machine edit

---

pack/baw.json
pack/rar.json

Fixes capitalization of ability in Tycoon and "trace" in Warroid Tracker.

Capitalization fixes

---

validate.py

Don't normalize minus sign or en-dash unicode characters in the JSON

---

pack/rar.json

see https://github.com/Alsciende/netrunnerdb/issues/451

make Mâché unique

---

pack/core.json
pack/tdatd.json

Fix two typos, reported in https://github.com/Alsciende/netrunnerdb/issues/450 and https://github.com/Alsciende/netrunnerdb/issues/449

fix 2 small typos

---

mwl.json
pack/mo.json
pack/mor.json
types.json

Add Salvaged Memories cards to historical MWLs, re-add influence cost to Timely Public Release

Proper case Ice, other small fixes

---

rotations.json

Pour one out (again) for some old faves...

Salvaged Memories is rotating out when Gateway and Update release.

---

cycles.json

thanks to @gereons for pointing this out.  I updated the server manually to unban all the ids. hehehehehe  lolsob

Mark sc-2019 and salvaged-memories as rotated.

---

mwl.json

step 1 of simplifying the "currents are banned" handling for NRDB.
This plus a couple of NRDB changes will mean i won't forget during the next banlist and accidentally list out every single current again.  :D

Add a subtypes banned list to each banlist object.

---

validate.py

For any cards with multiple printings, ensure that the text &
stripped_text fields are identical for every version of the card.
This passes at head (huzzah!) and is a good, small bit of defense until we have card / printing files.
Example output:
Validation error for card 'Sure Gamble': Found 2 different versions of text.
'Gain 9[credit].'
'Gain 9[credit] if you are cool.'
Validation error for card 'Sure Gamble': Found 2 different versions of stripped_text.
'Gain 9 credits.'
'Gain 9 credits if you are cool.'
Found 0 formatting and 2 validation errors

Add tests for matching {stripped_,}text fields.

---

pack/cd.json

Correct illustrator for Fractal Threat Matrix

---

README.md
schema/set_types_schema.json
set_types.json
validate.py

Starting to fill in the gaps for what is missing for NRDB v2 in the repo.

Add a set_types.json file and update validate.py

---

validate.py

Set an encoding and make it easier to run with ./validate.py

---

pack/si.json
printings/si.json

Add flavor text to Patron.

---

mwl.json
test/unit/index.ts

this test is silly right now, but we want the tests to be used for JSON schema validation as well, so i'm at least making this pass.  :D

Add an empty subtypes object to mwl and udpate test expectations.

---

.eslintrc.json
package-lock.json
package.json
src/index.ts
src/update-locales.ts

Adding lint for typescript, which will become more relevant as we ditch python in this repo.
Fix the errors found by lint in 2 of the typescript files.

Add lint script for typescript.

---

pack/msbp.json

Fixing bolding in costs in MSBP

Embolden costs in MSBP

---

package-lock.json
package.json
src/apply-text-updates.ts

Check in the tool I wrote to apply text updates from Rules team.

Apply text updates tool

---

factions.json
v2/factions.json

Address #547 in this repo, at least.  NRDB ... doesn't appear to use these colors, but i know the discord bot does and we may use them in other places.

Add faction colors for mini-factions.

---

pack/sg.json
src/index.ts
test/validate_v1_v2_equality.ts
test/validate_v2.ts
v2/printings/crimson_dust.json
v2/printings/data_and_destiny.json
v2/printings/democracy_and_dogma.json
v2/printings/draft.json
v2/printings/fear_and_loathing.json
v2/printings/honor_and_profit.json
v2/printings/midnight_sun_booster_pack.json
v2/printings/order_and_chaos.json
v2/printings/reign_and_reverie.json
v2/printings/system_core_2019.json
v2/printings/system_gateway.json
v2/printings/terminal_directive_cards.json
v2/printings/the_devil_and_the_dragon.json
v2/printings/the_valley.json
v2/printings/uprising.json

Additionally, validate card_set_id matches v2/printings/ file names.

Add tests for ensuring consistency between v1/v2 cards & printings.

---

test/validate_v1.ts
test/validate_v1_v2_equality.ts
test/validate_v2.ts

Change chai / expect import.

---

v2/card_pools/standard.json

sorry.  I was expecting the check to run before i merged the other PR, but maybe i was too hasty!

Fix sorting for new rotation.

---

test/validate_v2.ts
v2/card_subtypes.json

midnight sun cards had 2 new subtypes (harmonic and industrial).  The new API server card importer broke.

Remove repeated work, add test for v2 subtypes in cards.

---

v2/restrictions/eternal/eternal_points_list_21_11.json

Oops.
([Source](https://nullsignal.games/blog/revamp-of-the-eternal-format-21-11-released/))

Corrected date for Eternal Points List 21.11

---

pack/napd.json
v2/printings/napd_multiplayer.json

Dmitry Burmak was credited as "Dmitri Burnak" ([proof of correctness](https://images-cdn.fantasyflightgames.com/filer_public/2a/9e/2a9e3c68-0dd7-4b22-bf0d-25e55e1d8f11/adn_napdmultiplayeridentity.pdf))

Fixed illustrator credit on the NAPD Identity

---

pack/ms.json
v2/printings/midnight_sun.json

Updated Mestnichestvo's flavour text

---

pack/23s.json
pack/dc.json
pack/eas.json
pack/tdatd.json
v2/printings/23_seconds.json
v2/printings/daedalus_complex.json
v2/printings/earths_scion.json
v2/printings/the_devil_and_the_dragon.json

i found these missing while verifying the new printings for the v3 API.

Add missing illustrator credits.

---

pack/ur.json
v2/cards/aniccam.json

Remove errant period in Aniccam text.

---

pack/oac.json
v2/printings/order_and_chaos.json

Added flavour text for Qianju PT

Added flavour text for Qianju PT

---

schema/v2/cards_schema.json
schema/v2/printings_schema.json
test/validate_v1_v2_equality.ts
test/validate_v2.ts
v2/card_layouts.json
v2/card_subtypes.json
v2/cards/bmi_buffer.json
v2/cards/corporate_oversight.json
v2/cards/earth_station_sea_headquarters.json
v2/cards/evidence_collection.json
v2/cards/hoshiko_shiro_untold_protagonist.json
v2/cards/investigator_inez_delgado.json
v2/cards/investigator_inez_delgado_a.json
v2/cards/jinteki_biotech_life_imagined.json
v2/cards/lt_todachine.json
v2/cards/machicolation.json
v2/cards/sneakdoor_prime.json
v2/cards/surveillance_network_key.json
v2/cards/sync_everything_everywhere.json
v2/cards/the_masque.json
v2/printings/parhelion.json
v2/printings/terminal_directive_campaign.json
v2/printings/the_valley.json
v2/printings/uprising.json

- Adds the missing subtype from the flip sides of Biotech
- Fixes the name of Sneakdoor Prime A
- Updates the schema for faces
- `sides` -> `faces`
- `single_sided` -> `normal`

Added missing/broken data

---

v2/cards/abaasy.json
v2/cards/akhet.json
v2/cards/always_have_a_backup_plan.json
v2/cards/amaze_amusements.json
v2/cards/ampere_cybernetics_for_anyone.json
v2/cards/anemone.json
v2/cards/angelique_garza_correa.json
v2/cards/aniccam.json
v2/cards/anoetic_void.json
v2/cards/ansel_1_0.json

(not just affecting gateway cards, but this is silly).

Remove duplicate designed_by entries.

---

mwl.json
v2/formats/startup.json
v2/restrictions/standard/startup_ban_list_24_01.json
v2/restrictions/startup/startup_ban_list_24_01.json

This requires a copy of this list in standard as well for NRDB Classic.

Startup banlist

---

pack/cac.json
pack/dtwn.json
pack/rar.json
pack/ss.json
v2/cards/hangeki.json
v2/cards/scavenge.json
v2/cards/threat_assessment.json
v2/cards/wake_up_call.json

4 cards were reworded with the rules update today.

NCIGS rules update 

---

packs.json
v2/card_pools/standard.json
v2/card_sets.json

Add the pack and card set for Rebellion Without Rehearsal.

Add set for Rebellion Without Rehearsal.

---

v2/cards/cerebral_overwriter.json
v2/cards/colossus.json
v2/cards/daily_casts.json
v2/cards/self_modifying_code.json

I *think* this is it, but let me know if i missed any.

Fix remaining designed_by errors (that plural found).

---

pack/ph.json
v2/printings/parhelion.json

Fixes https://github.com/NetrunnerDB/netrunnerdb/issues/825

fix hafrun card vs json flavour

---

v2/formats/standard.json

Update card pools for most recent standard banlists.

---

mwl.json
v2/formats/startup.json
v2/restrictions/standard/startup_ban_list_24_09.json
v2/restrictions/startup/startup_ban_list_24_09.json

Goes live tomorrow morning hopefully

RIP Endurance ban in startup (24.09 banlist)

---

schema/v1/card_schema.json
schema/v2/cards_schema.json

👀 👀 👀 you know what this is for. 
Keeping v1 support because I'll probably try to update the V1 json to make deployment to NRDB easier given the amount of DOM changes it'll require.

Bio text attribute for _future_ stuff

---

mwl.json
test/validate_v2.ts
v2/card_pools/standard.json
v2/card_pools/startup.json
v2/formats/standard.json
v2/formats/startup.json
v2/restrictions/standard/standard_ban_list_25_04.json
v2/restrictions/standard/startup_balance_update_25_04_for_classic_only.json
v2/restrictions/startup/startup_balance_update_25_04.json

Updated to have the seventh rotation (Elevation), and then the new startup balance update (needs NRDB update, see separate PR), and Standard ban list.

New_ban_lists

---

cycles.json

Not sure if we need more, this is all I found so far though.

Elev release fixes - cycles update

---

pack/core.json
pack/core2.json
v2/printings/core_set.json
v2/printings/revised_core_set.json

Fix flavor text on Melange Mining Corp.

---

pack/uao.json
pack/ur.json
v2/cards/afterimage.json
v2/cards/labyrinthine_servers.json

Apply the fixes found for the Elevation Release Rules Text Update.

Apply fixes to Elevation release Rules Text update.

---

v2/cards/au_co_the_gold_standard_in_clones.json
v2/cards/azimat.json
v2/cards/bangun_when_disaster_strikes.json
v2/cards/biawak.json
v2/cards/bumi_1_0.json
v2/cards/dewi_subrotoputri_pedagogical_dhalang.json
v2/cards/hantu.json
v2/cards/madani.json
v2/cards/magdalene_keino_chemutai_cryptarchitect.json
v2/cards/mahkota_langit_grid.json
v2/cards/mercia_b4ll4rd.json
v2/cards/mitra_aman.json
v2/cards/muslihat_multifarious_marketeer.json
v2/cards/nebula_talent_management_making_stars.json
v2/cards/phat_gioan_baotixita.json
v2/cards/plutus.json
v2/cards/poetri_luxury_brands_all_the_rage.json
v2/cards/project_ingatan.json
v2/cards/pt_untaian_lifes_building_blocks.json
v2/cards/ryo_phoenix_ono_out_of_the_ashes.json
v2/cards/sang_kancil.json
v2/cards/semak_samun.json
v2/cards/syailendra.json
v2/cards/the_zwicky_group_invisible_hands.json
v2/cards/topan_ormas_leader.json

Elevation pronunciation guide Try 2

---

pack/tai.json
v2/cards/stegodon_mk_iv.json

separate PR for version tagging etc

stegodon typo fix

---

pack/ur.json
v2/cards/paules_cafe.json

fixes a formatting issue from the past

Paules cafe bump
