translations/de/cards.de.json

fixes keywords that weren't separated by " - " (long dashes were used instead)
fixes some deviations from the officially errata'd german text
fixes some typos

fixes for the german translation

---

pack/dt.json

Witness Tampering is a Gray Ops in addition of a Double.

en: Add missing subtype for Witness Tampering

---

pack/es.json

Sorry, missed a holdover from a copy/paste. This operation should not have a trash cost.

remove trash cost from Scarcity of Resources

---

pack/in.json

I didn't put `[trash]` in all lowercase so the symbol isn't appearing.

fix trash symbol on Citadel Sanctuary

---

pack/bm.json

In the new [FAQ 3.1.1](https://images-cdn.fantasyflightgames.com/filer_public/74/e6/74e67923-8d1e-45cd-a43c-314bacda2741/adn_faq_v311.pdf) Builder of Nations wording has changed.
Effective from the September 26th.

Update BoN with new wording from FAQ 3.1.1 Card Errata

---

pack/qu.json

Scoops images [here](http://imgur.com/a/x1S3p).
[Veritas](http://i.imgur.com/eu1xkWJ.png) seem to be from this pack as well, but I couldn't identify exactly the card number so I decided not to add it to these changes.

Add new Quorum card data from the FFG Worlds scoops

---

pack/so.json

- Minor update to the title of the new Criminal runner - `Los`
- Added card data for Clyde Van Rite based on the two scoops:
- [text scoops](https://www.reddit.com/r/Netrunner/comments/5b6f8o/spoiler_text_of_cards_leaked_at_worlds/)
- [image scoops](http://i.imgur.com/yejFKCD.jpg)

Add card data for Clyde Van Rite (Station One data pack)

---

pack/ml.json

The new Apex card, Reaver, has been [revealed](https://www.fantasyflightgames.com/en/news/2016/11/14/reaver/). 
image [here](https://images-cdn.fantasyflightgames.com/filer_public/aa/35/aa35ba57-b09d-4659-b8ed-1fbafe11639e/adn40_reaver.png)

Add new Apex card "Reaver" to Martial Law pack

---

packs.json

Martial Law is expected to be released on December 8th, 2016. Feel free to wait until it's FFG-official before merging this, if you want.

Add Martial Law release date

---

pack/ml.json

These em-dashes should not be included in-code, as is consistent with other traces.

Remove extraneous em-dashes

---

pack/eas.json

As pointed by Joel, the IDs don't have the flavour text and the extra text is contained in the title itself.

Fix card definition for Jinteki ID AgInfusion

---

pack/ml.json

On netrunnerdb.com, there are two "Stealth" entries in the "Subtype" search field. This may be why.

Remove trailing space from keywords

---

pack/dc.json
pack/ml.json
pack/om.json
pack/so.json
pack/st.json
pack/tc.json

As well as fixing some trivial misspellings, I've taken the liberty of homogenising a couple of names. Specifically, I've renamed all instances of `Zefanya Maega` to `Zefanya Langkan Maega`, and one instance of `Matthew Zeilinger` to `Matt Zeilinger`.
While the previous state of the data does accurately reflect the cards (e.g. Zefanya's middle name is used on Fast Track, but not on John Masanori), I feel that the ability to search by a single, consistent name across all cards is more useful than strict adherence to physical card text.
I chose the long-form of Zefanya's name on the basis that it was most recently used (in Honor and Profit, as opposed to previous short-form uses in the Spin Cycle), and chose Matt as opposed to Matthew Zeilinger because come on, who calls him Matthew …

Fix duplicate and misspelt artist names

---

pack/td.json

Article:
https://www.fantasyflightgames.com/en/news/2017/4/12/access-points/
Also, the articles makes available images for some of the cards already
spoiled:
- [Process Automation](https://images-cdn.fantasyflightgames.com/filer_public/7c/b7/7cb73cd3-568b-4ee5-88ad-9f676e54e3b6/adn42-process-automation.png)
- [Adept](https://images-cdn.fantasyflightgames.com/filer_public/de/7d/de7d887e-3b14-49d4-b062-7af7ccbb664b/adn42-adept.png)
- [Mammon](https://images-cdn.fantasyflightgames.com/filer_public/af/4d/af4dd5b6-62bd-4f2f-8a27-0e6ecb3a9632/adn42-mammon.png)
- [Biometric Spoofing](https://images-cdn.fantasyflightgames.com/filer_public/f5/88/f588ab85-4605-4cbd-98fd-acbe54aff9c5/adn42-biometric-spoofing.png)

Add new card spoiled for TD in Access Point FFG article

---

pack/cd.json

add missing subtype to Salvaged Vanadis Armory

---

translations/de/pack/td.de.json

fix typos in Black Level Clearance
@Alsciende it'd be great if you could merge this into production soon, the current empty translation record for UVC creates problem for Net Deck (which I'll fix of course, but that will take some time)

add missing translation for Ultraviolet Clearance

---

pack/baw.json

Added "this run" as per card text (sorry, Mass-Driver fans).

fix to mass-driver text

---

cycles.json

Marked `Core`, `Spin`, and `Genesis` as rotated in `cycles.json`
Also saw that there was a `rotations.json` file, should I be using that instead of the `rotated` flag? If so, let's remove the `rotated` field.

Updating cycles for Oct 2017 rotation

---

pack/core.json
pack/ka.json
pack/tdatd.json

Fixed up some typos for spoiled Kitara cards for clarity/accuracy.
In addition, I removed the errata from AstroScript.  As per the most recent FAQ, Astro no longer has errata due to rotation, so the "Limit 1 per deck" is not in force.

typos in kitara cards; removed astro errata

---

pack/dtwn.json

Fixed a missing comma and incorrectly capitalized t in Trace 3 for Forced Connection.

Fix typos in Forced Connection

---

pack/ka.json

The text on Flame-out is slightly awkward English, but it is what is printed on the spoiled KA cards.

fix typos for Flame-out and Kasi String

---

pack/core2.json

Never even noticed until today, randomly. I didn't include this, but maybe the errata tag could get taken off the Revised Core version of Punitive Counterstrike, since the card now matches.

Shipment from Mirrormorph new text in Revised Core

---

pack/ka.json

Image and cardgamedb says that NEXT Diamond costs 4 influence, data previously had it at 5.

Fixed influence cost of NEXT Diamond

---

pack/dtwn.json
pack/ml.json
pack/td.json

Show of Force, Paper Trail, and SSL Endorsement are missing "faction_cost". Easily missed as Agendas don't require a faction_cost, but that only applies to non-neutral agendas.

Fixes missing influence values

---

packs.json

Quantity for SC19 was 148, but should be 147, which was causing the "Browse by set" list for example to show it as "147/148" despite all cards being included.

Fixed card quantity for SC19.

---

pack/core.json

Added errata from FAQ 3.1 to Astroscript Pilot Program (Limit 1 per deck). With Eternal format out there now, it's probably worth fixing this.
In the process, I seem to have broken my local dev environment, so cannot fully test that this works as expected - I can see that the errata show on the card page as expected, but I didn't get a chance to test whether the cards is now limited to a quantity of 1 on the Build tab of deckbuilder, so if someone could give this a pull and check before merging it, that would be great!
Pending successful tests, I believe this resolves [this issue](https://github.com/Alsciende/netrunnerdb/issues/29) from the netrunnerdb repo.

Added Astro errata

---

pack/df.json

from https://theflatline.net/2019/02/28/blueberry-spoilers-niseis-downfall-community-week/

flatline scoops

---

pack/baw.json
pack/core.json
pack/core2.json
pack/cotc.json
pack/dad.json
pack/df.json
pack/dt.json
pack/fc.json
pack/ftm.json
pack/ml.json
pack/mt.json
pack/oh.json
pack/sc19.json
pack/ss.json
pack/tc.json
pack/td.json
pack/uao.json
pack/win.json
pack/wla.json

Includes all new errata issued in the Comprehensive Rules 1.2 update, along with moving Thoth to it's correct place in the json (no function change) and changing the `<em>` tag to an `<i>` tag on the recommendation of a number of people.

CR 1.2 Errata

---

pack/cotc.json
pack/win.json

Removes `null` strength from Trypano and eXer.

Non-icebreakers can't have null strength

---

pack/win.json

Correct Masvingo flavor text

---

pack/core2.json

Fixed this in Original Core, but the issue was present in the Revised Core and System Core 2019 data too. This fixes Revised Core.

Fix Hadrian's Wall flavor text capitalization

---

pack/mo.json

Sorry for this orphan pull request; I accidentally made this its own branch instead of editing my `master` branch.
Anyway, this fixes typos in the text of both Watch the World Burn and Hired Help.

Fix typos in Watch the World Burn and Hired Help

---

mwl.json

Each of the included entries is a different printing/version than the one at release, which is why it's not included. The cards are Eli 1.0, Aesop's Pawnshop, and Magnum Opus.

Add missing versions

---

pack/mt.json

I already SCPed an updated card image onto production, so this just makes the text match the image now.

Added Interns errata from 2nd FFG printing

---

pack/ur.json
pack/urbp.json

Replaced a `<strong>` tag in Buffer Drive's flavor text with `<em>`.
Added `<strong>` tags around card subtypes in text of Afterimage, Euler, Penrose, DreamNet, etc.
Fixed recurring credit in Mantle.
Corrected an error in The Back's text ("each run" ➡️ "each turn") and bolded the non-click text in the paid ability's cost.
Other general copy-editing (periods, word order).

Minor corrections to Uprising cards

---

cycles.json

Who knew? This is done here and not in NRDB itself based on the `rotations.json`  🤷‍♂

Rotated C&C and Lunar

---

pack/ur.json

As spotted by Jamie from Rules, the card text for the Uprising version of Daily Casts was not updated.

Updated card text for Daily Casts in Uprising

---

pack/core.json

@NoahTheDuke took the errata too literally:
```
11.2.6. Zaibatsu Loyalty (Original Core 71)
a. Should read: “[interrupt]– When a card would be exposed, you may rez this asset.”
```
😛 😝

Fixed issue where card ability had been entirely overwritten

---

README.md
pack/oac.json
pack/ur.json
pack/urbp.json

Turns out, the database text for Cybertrooper Talut has been subtly wrong ("until the end of the turn" vs. "for the remainder of the turn") this whole time! Fixed in Uprising and Uprising Booster Pack.
Also fixed the flavor text of Virus Breeding Ground and changed the readme so that it shows the modern NISEI style for traces (with square brackets instead of superscript).

Minor copy-editing

---

pack/ur.json

Adds the "Division" keyword to _Earth Station: SEA Headquarters_ as seen on the card itself. For reference: https://netrunnerdb.com/en/card/26120

Add keywords to Earth Station

---

pack/ur.json

Aniccam was using the HTML entity `&mdash;`, which wasn't rendering. I replaced it with the Unicode character —.

Correct malformed em dash in Aniccam's FT

---

pack/sg.json
pack/su21.json

* Converted bullets to unordered lists
* Wrapped non-credit costs in `<strong>` tags
* Removed `{ca}` tags in Corroder FT

Tidy up SG and SU21 cards

---

pack/sg.json
pack/su21.json

Fix Vitruvius' cost in SU21 (make it bold) and remove the layout tags in Whitespace's FT.
Haven't yet gotten to updating the formatting for other versions of SU21 cards (so Vitruvius in SC19 doesn't have a bold cost yet).

Fix Vitruvius cost and Whitespace FT

---

rotations.json
schema/rotations_schema.json
validate.py

This inverts the logic of `rotations.json` - instead of listing what's legal after this rotation, we now specify what's rotating out.
This PR requires a db schema change in NetrunnerDB, see https://github.com/NetrunnerDB/netrunnerdb/pull/512

New rotations format

---

pack/sg.json

VRcation is unique in using standard escaped double quotation marks in its flavor text. I assume this is an error.

Fixed VRcation's quotation marks

---

cards/secure_and_protect.json
cards/storgotic_resonator.json
cards/whistleblower.json
pack/df.json
printings/df.json

A few cards in Ashes use the wrong tags for italics. This updates them to the existing standard of using `<em>`.

Removed all instances of <i> and replaced them with <em>

---

schema/v2/card_cycles_schema.json
schema/v2/card_sets_schema.json
test/validate_v1_v2_equality.ts
v2/card_cycles.json
v2/card_sets.json

This enables interop with NRDB classic.  We had printing codes, but not legacy codes for card sets and card cycles.

Add legacy_code fields to Card Cycles and Sets.

---

v2/card_pools/startup.json

We had a slightly wonky specification for the card pools here.
I'll add a test as a followup, but card pools should list cycles for any cycles that are completely encompassed and the sets should also be spelled out explicitly.
It's OK to have 1 set from a cycle specified, but not to have a missing set from a cycle for eternal, standard, snapshot, or startup.

Fix cycle and set specification for startup card pools.

---

schema/v2/card_set_types_schema.json
v2/card_set_types.json
v2/card_sets.json

- Added `booster_pack` as a set type to represent the new trend of releasing booster packs next to full releases
- Made Salvaged Memories an expansion
- Made the constructed Terminal Directive set a deluxe
My reasoning for changing SM and TD from being data packs is it feels inaccurate to call a set that wasn't part of a cycle a data pack. I'm happy to revert these if they make more sense as data packs.
Here's how I'm viewing each type:
- booster_pack (a booster pack; so far a direct subset of another set)
- campaign (Terminal Directive Campaign)
- core (the core sets and system update)
- data_pack (the major releases of each cycle; 6 per FFG cycle and 2 per NISEI cycle)
- deluxe (a set released in a big box)
- draft (draft)
- expansion (miscellaneous Standard set)
- promo (official …

Cleaned up card set types

---

cycles.json

This fixes the set display (at least the text part).
Before:
After:

Set Liberation cycle to size 2 (2 packs).

---

pack/df.json
pack/ms.json
v2/cards/endurance.json
v2/cards/masterwork_v37.json

1. Endurance is missing a space between "+2" and "MU" (in its `stripped_text`)
2. Masterwork has an errant period at the end of its "+1 MU"

MU notation fixes for Endurance and Masterwork.

---

pack/rwr.json
v2/cards/business_as_usual.json

Incorrect closing `</ul>` and `</li>` placement.
https://netrunnerdb.com/en/card/34128

Fix formatting of Business as Usual 34128 card text

---

mwl.json

This pushes sunset down in the list.  We can't delete it without work that probably isn't worth doing.

Change start date for Sunset to move it back in time.

---

pack/df.json
pack/ur.json
v2/printings/downfall.json
v2/printings/uprising.json

Fixes #836  and the same issue for Stargate.

Fix unclosed em tags in flavor text.

---

v2/formats/startup.json

We missed this a while back so https://netrunnerdb.com/en/formats is showing the wrong thing.

startup_liberation is active Startup card pool.

---

pack/sg.json
v2/printings/system_gateway.json

During the Remaster import we have erroneous flavour text for spin doctor. This should remove the extra line from Funhouse's flavour text that snuck in.

removed Funhouse Flavour Text from Spin Doctor

---

v2/formats/standard.json

needed to tie this to the format.  Without this it doesn't show up on the NRDB classic ban list page.

Add banlist 24-12 to standard format.
